sudo: required

services:
  - docker

before_install:
  - docker build -t asfandyar9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run asfandyar9/react-test npm test -- --coverage

after_success:
  - docker build -t asfandyar9/multi-client ./client
  - docker build -t asfandyar9/multi-nginx ./nginx
  - docker build -t asfandyar9/multi-server ./server
  - docker build -t asfandyar9/multi-worker ./worker

#Log in to docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
- docker push asfandyar9/multi-client
- docker push asfandyar9/multi-nginx
- docker push asfandyar9/multi-server
- docker push asfandyar9/multi-worker